[build]
  command = "rm -rf dist/assets && vite build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  included_files = ["dist/assets/**"]

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

