[build]
  command = "rm -rf dist/assets && vite build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  included_files = ["dist/assets/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

