[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  included_files = ["dist/assets/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
